=== sitara2423/AI-202409D1json/XML/external.dtd
<!ELEMENT aptech (staff*,student*)>
<!ELEMENT staff (id , name , email)>
<!ELEMENT student (id , name , course)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT course (#PCDATA)>
<!ATTLIST staff department CDATA #REQUIRED>
<!ENTITY aptech SYSTEM "aptech shahrah-e-faisal">

=== sitara2423/AI-202409D1json/XML/external.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aptech SYSTEM "external.dtd">
<aptech>
    <staff department="HR">
        <id></id>
        <name></name>
        <email></email>
    </staff>
    <staff department="HR">
        <id></id>
        <name></name>
        <email></email>
    </staff>
    <student>
        <id></id>
        <name></name>
        <course></course>
    </student>
</aptech>
