<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aptech [
<!ELEMENT aptech (student , employee)>
<!ELEMENT student (id , name , email)>
<!ELEMENT employee (id , name , salary)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
<!--<!ATTLIST student aptech CDATA #REQUIRED-->
<!ATTLIST student aptech CDATA #FIXED 'SFC'>
<!ENTITY my "aptech shahrah-e-faisal">
]>
<aptech>
    <student aptech='SFC'> 
        <id></id>
        <name></name>
        <email></email>
    </student>
    <student aptech='SFC'> 
        <id></id>
        <name></name>
        <email></email>
    </student>


    <employee>
        <id></id>
        <name></name>
        <salary></salary>
    </employee>
</aptech>